service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

functions:
  execute:
    handler: src/handler.execute
    events:
      - schedule: cron(35 19 * * ?)